export const navPermissionMap: Record<string, string> = {
    dashboard: 'NAV_DASHBOARD',
    employees: 'NAV_EMPLOYEES',
    partners: 'NAV_PARTNERS',
    requirements: 'NAV_REQUIREMENTS',
    workspace: 'NAV_WORKSPACE',
    tasks: 'NAV_TASKS',
    reports: 'NAV_REPORTS',
    calendar: 'NAV_CALENDAR',
    leaves: 'NAV_LEAVES',
    invoices: 'NAV_INVOICES',
    notes: 'NAV_NOTES',
    meetings: 'NAV_MEETINGS',
    feedback: 'NAV_FEEDBACK',
};
